from pandas import Series

groups = Series(
    {
        'Avestruz': 1,
        'Águia': 2,
        'Burro': 3,
        'Borboleta': 4,
        'Cachorro': 5,
        'Cabra': 6,
        'Carneiro': 7,
        'Camelo': 8,
        'Cobra': 9,
        'Coelho': 10,
        'Cavalo': 11,
        'Elefante': 12,
        'Galo': 13,
        'Gato': 14,
        'Jacaré': 15,
        'Leão': 16,
        'Macaco': 17,
        'Porco': 18,
        'Pavão': 19,
        'Peru': 20,
        'Touro': 21,
        'Tigre': 22,
        'Urso': 23,
        'Veado': 24,
        'Vaca': 25
    }
)

numbers = Series(
    {
        1: 'Avestruz',
        2: 'Avestruz',
        3: 'Avestruz',
        4: 'Avestruz',
        5: 'Águia',
        6: 'Águia',
        7: 'Águia',
        8: 'Águia',
        9: 'Burro',
        10: 'Burro',
        11: 'Burro',
        12: 'Burro',
        13: 'Borboleta',
        14: 'Borboleta',
        15: 'Borboleta',
        16: 'Borboleta',
        17: 'Cachorro',
        18: 'Cachorro',
        19: 'Cachorro',
        20: 'Cachorro',
        21: 'Cabra',
        22: 'Cabra',
        23: 'Cabra',
        24: 'Cabra',
        25: 'Carneiro',
        26: 'Carneiro',
        27: 'Carneiro',
        28: 'Carneiro',
        29: 'Camelo',
        30: 'Camelo',
        31: 'Camelo',
        32: 'Camelo',
        33: 'Cobra',
        34: 'Cobra',
        35: 'Cobra',
        36: 'Cobra',
        37: 'Coelho',
        38: 'Coelho',
        39: 'Coelho',
        40: 'Coelho',
        41: 'Cavalo',
        42: 'Cavalo',
        43: 'Cavalo',
        44: 'Cavalo',
        44: 'Cavalo',  
        45: 'Elefante',
        46: 'Elefante',
        47: 'Elefante',
        48: 'Elefante',
        49: 'Galo',
        50: 'Galo',
        51: 'Galo',
        52: 'Galo',
        53: 'Gato',
        54: 'Gato',
        55: 'Gato',
        56: 'Gato',
        57: 'Jacaré',
        58: 'Jacaré',
        59: 'Jacaré',
        60: 'Jacaré',
        61: 'Leão',
        62: 'Leão',
        63: 'Leão',
        64: 'Leão',
        65: 'Macaco',
        66: 'Macaco',
        67: 'Macaco',
        68: 'Macaco',
        69: 'Porco',
        70: 'Porco',
        71: 'Porco',
        72: 'Porco',
        73: 'Pavão',
        74: 'Pavão',
        75: 'Pavão',
        76: 'Pavão',
        77: 'Peru',
        78: 'Peru',
        79: 'Peru',
        80: 'Peru',
        81: 'Touro',
        82: 'Touro',
        83: 'Touro',
        84: 'Touro',
        85: 'Tigre',
        86: 'Tigre',
        87: 'Tigre',
        88: 'Tigre',
        89: 'Urso',
        90: 'Urso',
        91: 'Urso',
        92: 'Urso',
        93: 'Veado',
        94: 'Veado',
        95: 'Veado',
        96: 'Veado',
        97: 'Vaca',
        98: 'Vaca',
        99: 'Vaca',
        100: 'Vaca',
        0: 'Vaca',
    }
)

gifts = Series(
    {
        '1 premio' : 'Férias! Tem direito a 1 hora de férias',
        '2 premio' : 'Dinheiro, os impostos cobriram o valor',
        '3 premio' : 'R$ 100 em compras, jaja chega o pix',
        '4 premio' : 'Viagem de avião, mas você tem medo de avião',
        '5 premio' : 'Parabéns'
    }
)
